export { default as BaseBorder } from './BaseBorder.vue'
export { default as GradientBorder } from './GradientBorder.vue'
export { default as PolygonBorder1 } from './polygonBorders/PolygonBorder1.vue'
export { default as PolygonBorder2 } from './polygonBorders/PolygonBorder2.vue'
export { default as PolygonBorder3 } from './polygonBorders/PolygonBorder3.vue'
export { default as PolygonBorder4 } from './polygonBorders/PolygonBorder4.vue'
export { default as PolygonBorder5 } from './polygonBorders/PolygonBorder5.vue'
export { default as PolygonBorder6 } from './polygonBorders/PolygonBorder6.vue'

export { default as RectBorder } from './RectBorder.vue'
